const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const brands = [
  'Panadol', 'Augmentin', 'Amoxil', 'Brufen', 'Flagyl', 'Ventolin', 'Losec', 'Zantac',
  'Nexium', 'Lipitor', 'Risek', 'Glucophage', 'Lantus', 'Humulin', 'Ciprol', 'Zithromax',
  'Rovamycin', 'Diamicron', 'Concor', 'Co-Approvel', 'Avamys', 'Seretide', 'Xanax',
  'Lexotanil', 'Valium', 'Calcitonin', 'Neurobion', 'Ferrofol', 'Obimin', 'Ponstan',
  'Voltral', 'Arcoxia', 'Lyrica', 'Prozac', 'Xalacom', 'Tobrex', 'Maxitrol', 'Betnovate',
  'Canesten', 'Nizoral', 'Allegra', 'Claritin', 'Zyrtec', 'Aerius', 'Singulair',
  'Pulmicort', 'Symbicort', 'Atrovent', 'Spiriva', 'Foradil', 'Serevent', 'Flixotide',
  'Lasix', 'Aldactone', 'Cardicor', 'Tarka', 'Tritace', 'Coveram', 'Coversyl', 'Lopressor',
  'Inderal', 'Atenolol', 'Tenormin', 'Norvasc', 'Plendil', 'Adalat', 'Procardia',
  'Isoptin', 'Diltiazem', 'Cardizem', 'Lanoxin', 'Digoxin', 'Cordarone', 'Rytmonorm',
  'Mexitil', 'Etopin', 'Crestor', 'Zocor', 'Mevacor', 'Pravachol', 'Lescol', 'Lofibra',
  'Tricor', 'Ezetrol', 'Vytorin', 'Omacor', 'Lovaza', 'Actos', 'Avandia', 'Januvia',
  'Galvus', 'Onglyza', 'Trajenta', 'Jardiance', 'Invokana', 'Forxiga', 'Victoza',
  'Byetta', 'Janumet', 'Eucreas', 'Amaryl', 'Daonil', 'Euglucon', 'Glurenorm',
  'Starlix', 'NovoNorm', 'Glucobay', 'Bayer', 'Acarbose', 'Insulatard', 'Actrapid',
  'Mixtard', 'NovoRapid', 'NovoMix', 'Levemir', 'Tresiba', 'Humalog', 'HumalogMix',
  'Apidra', 'Ryzodeg', 'Xultophy', 'Soliqua', 'Fiasp', 'Clexane', 'Fragmin',
  'Innohep', 'Lovenox', 'Arixtra', 'Eliquis', 'Pradaxa', 'Xarelto', 'Warfarin',
  'Plavix', 'Ticlid', 'Aggrenox', 'Persantine', 'Aspirin', 'Disprin', 'Micropirin',
  'Ecotrin', 'Bokey', 'Clopidogrel', 'Prasugrel', 'Ticagrelor', 'Brilinta', 'Effient',
  'AmBisome', 'Fungizone', 'Mycamine', 'Cancidas', 'Diflucan', 'Sporanox', 'Lamisil',
  'Griseofulvin', 'Nystatin', 'Flucan', 'Itranox', 'Terbinaforce', 'Ketoconazole',
  'Clotrimazole', 'Miconazole', 'Econazole', 'Tioconazole', 'Bifonazole', 'Sertaconazole',
  'Zovirax', 'Valtrex', 'Famvir', 'Denavir', 'Vectavir', 'Aciclovir', 'Valaciclovir',
  'Famciclovir', 'Penciclovir', 'Ganciclovir', 'Valganciclovir', 'Cymevene', 'Valcyte',
  'Rebetol', 'Copegus', 'Ribavirin', 'Pegasys', 'PegIntron', 'ViraferonPeg', 'IntronA',
  'RoferonA', 'Avonex', 'Rebif', 'Betaferon', 'Extavia', 'Copaxone', 'Glatiramer',
  'Tysabri', 'Gilenya', 'Fingolimod', 'Aubagio', 'Tecfidera', 'DimethylFumarate',
  'Lemtrada', 'Mavenclad', 'Kesimpta', 'Ocrevus', 'Briumvi', 'Tyruko', 'Uplizna',
  'Zeposia', 'Ponvory', 'Mayzent', 'Siponimod', 'Amben', 'Dostinex', 'Parlodel',
  'Cabergoline', 'Bromocriptine', 'Quinagolide', 'Norprolac', 'Somatostatin', 'Sandostatin',
  'Lanreotide', 'Somatuline', 'Pasireotide', 'Signifor', 'Mestinon', 'Pyridostigmine',
  'Neostigmine', 'Prostigmin', 'Zanaflex', 'Tizanidine', 'Baclofen', 'Lioresal',
  'Dantrolene', 'Dantrium', 'Sirdalud', 'Myoxane', 'Robaxin', 'Methocarbamol',
  'Soma', 'Carisoprodol', 'Flexeril', 'Cyclobenzaprine', 'Norflex', 'Orphenadrine',
  'Lioresal', 'Baclofen', 'Diazepam', 'Valium', 'Clonazepam', 'Rivotril', 'Klonopin',
  'Lorazepam', 'Ativan', 'Alprazolam', 'Xanax', 'Bromazepam', 'Lexotanil', 'Lexomil',
  'Nitrazepam', 'Mogadon', 'Flunitrazepam', 'Rohypnol', 'Midazolam', 'Dormicum',
  'Versed', 'Temazepam', 'Restoril', 'Oxazepam', 'Serax', 'Prazepam', 'Centrax',
  'Chlordiazepoxide', 'Librium', 'Clorazepate', 'Tranxene', 'Zolpidem', 'Ambien',
  'Stilnox', 'Zopiclone', 'Imovane', 'Zimovane', 'Eszopiclone', 'Lunesta',
  'Zaleplon', 'Sonata', 'Ramelteon', 'Rozerem', 'Suvorexant', 'Belsomra',
  'Doxepin', 'Silenor', 'Trazodone', 'Desyrel', 'Mirtazapine', 'Remeron',
  'Amitriptyline', 'Elavil', 'Nortriptyline', 'Pamelor', 'Imipramine', 'Tofranil',
  'Clomipramine', 'Anafranil', 'Trimipramine', 'Surmontil', 'Doxepin', 'Adaptin',
  'Sinequan', 'Amoxapine', 'Asendin', 'Maprotiline', 'Ludiomil', 'Desipramine',
  'Norpramin', 'Protriptyline', 'Vivactil', 'Phenelzine', 'Nardil', 'Tranylcypromine',
  'Parnate', 'Isocarboxazid', 'Marplan', 'Selegiline', 'Emsam', 'Eldepryl',
  'Citalopram', 'Celexa', 'Escitalopram', 'Lexapro', 'Fluoxetine', 'Prozac',
  'Paroxetine', 'Paxil', 'Sertraline', 'Zoloft', 'Fluvoxamine', 'Luvox',
  'Vortioxetine', 'Trintellix', 'Brintellix', 'Vilazodone', 'Viibryd',
  'Duloxetine', 'Cymbalta', 'Venlafaxine', 'Effexor', 'Desvenlafaxine', 'Pristiq',
  'Khedezla', 'Levomilnacipran', 'Fetzima', 'Milnacipran', 'Ixel', 'Savella',
  'Bupropion', 'Wellbutrin', 'Zyban', 'Contrave', 'Methylphenidate', 'Ritalin',
  'Concerta', 'Daytrana', 'Metadate', 'Quillivant', 'Aptensio', 'Adhansia',
  'Azstarys', 'Jornay', 'Cotempla', 'Relexxii', 'Dexmethylphenidate', 'Focalin',
  'Dexedrine', 'Adderall', 'Vyvanse', 'Lisdexamfetamine', 'Mydayis', 'Evekeo',
  'Zenzedi', 'ProCentra', 'Strattera', 'Atomoxetine', 'Intuniv', 'Guanfacine',
  'Kapvay', 'Clonidine', 'Catapres', 'Tenex', 'Qelbree', 'Viloxazine',
  'Memantine', 'Namenda', 'Namzaric', 'Donepezil', 'Aricept', 'Rivastigmine',
  'Exelon', 'Galantamine', 'Razadyne', 'Reminyl', 'Tacrine', 'Cognex',
  'Levodopa', 'Sinemet', 'Rytary', 'Duopa', 'Carbidopa', 'Lodosyn',
  'Pramipexole', 'Mirapex', 'Ropinirole', 'Requip', 'Rotigotine', 'Neupro',
  'Apomorphine', 'Apokyn', 'Selegiline', 'Eldepryl', 'Zelapar', 'Rasagiline',
  'Azilect', 'Safinamide', 'Xadago', 'Entacapone', 'Comtan', 'Stalevo',
  'Tolcapone', 'Tasmar', 'Benztropine', 'Cogentin', 'Trihexyphenidyl', 'Artane',
  'Procyclidine', 'Kemadrin', 'Biperiden', 'Akineton', 'Orphenadrine', 'Disipal',
  'Amantadine', 'Symmetrel', 'Gocovri', 'Osmolex', 'Istradefylline', 'Nourianz',
  'Tetrabenazine', 'Xenazine', 'Deutetrabenazine', 'Austedo', 'Valbenazine',
  'Ingrezza', 'Riluzole', 'Rilutek', 'Tiglutik', 'Exservan', 'Radicava',
  'Edaravone', 'Albrioza', 'SodiumPhenylbutyrate', 'Tursed', 'Relyvrio',
  'AMX0035', 'Methylcobalamin', 'Mecobalamin', 'MethylB12', 'Coban', 'Mcobal',
  'Cynobal', 'Neuromin', 'Gabapentin', 'Neurontin', 'Gralise', 'Horizant',
  'Gabarone', 'Fanatrex', 'Pregabalin', 'Lyrica', 'Carbamazepine', 'Tegretol',
  'Carbatrol', 'Equetro', 'TegretolXR', 'Oxcarbazepine', 'Trileptal', 'Oxtellar',
  'Eslicarbazepine', 'Aptiom', 'Topiramate', 'Topamax', 'Trokena', 'Topiragen',
  'Lamotrigine', 'Lamictal', 'Subvenite', 'Valproate', 'Depakote', 'Depakene',
  'Stavzor', 'ValproicAcid', 'Divalproex', 'Phenytoin', 'Dilantin', 'Phenytek',
  'Fosphenytoin', 'Cerebyx', 'Levetiracetam', 'Keppra', 'Elepsia', 'Spritam',
  'Roweepra', 'Briviact', 'Brilivar', 'Brivaracetam', 'Zonisamide', 'Zonegran',
  'Zonisade', 'Lacosamide', 'Vimpat', 'Motpol', 'Perampanel', 'Fycompa',
  'Rufinamide', 'Banzel', 'Felbamate', 'Felbatol', 'Tiagabine', 'Gabitril',
  'Vigabatrin', 'Sabril', 'Ethosuximide', 'Zarontin', 'Methsuximide', 'Celontin',
  'Phensuximide', 'Milontin', 'Trimethadione', 'Tridione', 'Paramethadione',
  'Paradione', 'Acetazolamide', 'Diamox', 'Clobazam', 'Onfi', 'Frisium',
  'Stiripentol', 'Diacomit', 'Cannabidiol', 'Epidiolex', 'Fenfluramine',
  'Fintepla', 'Clonazepam', 'Rivotril', 'Diazepam', 'Diastat', 'Valtoco',
  'Midazolam', 'Nayzilam', 'Methylprednisolone', 'Medrol', 'Prednisolone',
  'Omnipred', 'Prednisone', 'Deltasone', 'Hydrocortisone', 'Cortef', 'SoluCortef',
  'Dexamethasone', 'Decadron', 'Ozurdex', 'Betamethasone', 'Celestone',
  'Triamcinolone', 'Kenalog', 'Aristocort', 'Fluticasone', 'Flovent', 'Flixonase',
  'Budesonide', 'Pulmicort', 'Rhinocort', 'Entocort', 'Uceris', 'Mometasone',
  'Nasonex', 'Asmanex', 'Beclomethasone', 'Qvar', 'Beconase', 'Becloforte',
  'Ciclesonide', 'Alvesco', 'Zetonna', 'Flunisolide', 'Aerobid', 'Nasalide',
  'Hydroxychloroquine', 'Plaquenil', 'Chloroquine', 'Aralen', 'Quinacrine',
  'Atabrine', 'Mefloquine', 'Lariam', 'Quinine', 'Qualaquin', 'Artemether',
  'Lumefantrine', 'Coartem', 'Artemisin', 'Artesunate', 'Artemotil', 'Arteether',
  'Doxycycline', 'Vibramycin', 'Monodox', 'Acticlate', 'Doryx', 'Alodox',
  'Minocycline', 'Minocin', 'Solodyn', 'Arestin', 'Dynacin', 'Tetracycline',
  'Sumycin', 'Achromycin', 'Tetracon', 'Chlortetracycline', 'Aureomycin',
  'Oxytetracycline', 'Terramycin', 'Tigecycline', 'Tygacil', 'Eravacycline',
  'Xerava', 'Omadacycline', 'Nuzyra', 'Sarecycline', 'Seysara', 'Azithromycin',
  'Zithromax', 'Azasite', 'Zmax', 'Clarithromycin', 'Biaxin', 'Prevpac',
  'Erythromycin', 'Eryc', 'EryPed', 'EryTab', 'EES', 'PCE', 'Erygel',
  'Roxithromycin', 'Rulide', 'Zithromax', 'Fidaxomicin', 'Dificid', 'Solithromycin',
  'Telithromycin', 'Ketek', 'Ciprofloxacin', 'Cipro', 'Ciloxan', 'Cetraxal',
  'Proquin', 'Levofloxacin', 'Levaquin', 'Quixin', 'Iquix', 'Moxifloxacin',
  'Avelox', 'Moxeza', 'Vigamox', 'Gatifloxacin', 'Zymaxid', 'Tequin',
  'Gemifloxacin', 'Factive', 'Ofloxacin', 'Floxin', 'Ocuflox', 'Norfloxacin',
  'Noroxin', 'Chibroxin', 'Lomefloxacin', 'Maxaquin', 'Sparfloxacin', 'Zagam',
  'Enoxacin', 'Penetrex', 'Delafloxacin', 'Baxdela', 'Clinafloxacin', 'NalidixicAcid',
  'NegGram', 'Fleroxacin', 'Quinodis', 'Pefloxacin', 'Peflacine', 'Rufloxacin',
  'Prulifloxacin', 'Garenoxacin', 'Besifloxacin', 'Besivance', 'Ozenoxacin',
  'Xepi', 'Nadifloxacin', 'Acuatim', 'Zabofloxacin', 'Wonlevy', 'Finflox',
  'Amoxicillin', 'Amoxil', 'Trimox', 'Moxatag', 'Augmentin', 'Ampicillin',
  'Principen', 'Unasyn', 'Penicillin', 'PenVeeK', 'Pfizerpen', 'Bicillin',
  'Cloxacillin', 'Tegopen', 'Dicloxacillin', 'Dynapen', 'Pathocil', 'Nafcillin',
  'Unipen', 'Methicillin', 'Staphcillin', 'Oxacillin', 'Bactocill', 'Piperacillin',
  'Pipracil', 'Zosyn', 'Ticarcillin', 'Ticar', 'Timentin', 'Carbenicillin',
  'Geocillin', 'Geopen', 'Azlocillin', 'Azlin', 'Mezlocillin', 'Mezlin',
  'Cephalexin', 'Keflex', 'Keftab', 'Cephadrine', 'Velosef', 'Cefadroxil',
  'Duricef', 'Cefzil', 'Cefprozil', 'Cefaclor', 'Ceclor', 'Cefdinir', 'Omnicef',
  'Cefixime', 'Suprax', 'Cefpodoxime', 'Vantin', 'Cefuroxime', 'Ceftin', 'Zinacef',
  'Cefotaxime', 'Claforan', 'Ceftriaxone', 'Rocephin', 'Ceftazidime', 'Fortaz',
  'Tazicef', 'Cefepime', 'Maxipime', 'Cefiderocol', 'Fetroja', 'Ceftobiprole',
  'Zevtera', 'Ceftaroline', 'Teflaro', 'Cefalotin', 'Keflin', 'Cephapirin',
  'Cefadyl', 'Cefoxitin', 'Mefoxin', 'Cefotetan', 'Cefotan', 'Cefmetazole',
  'Zefazone', 'Ertapenem', 'Invanz', 'Meropenem', 'Merrem', 'Doripenem',
  'Doribax', 'Imipenem', 'Primaxin', 'Cilastatin', 'Primaxin', 'Faropenem',
  'Farom', 'Biapenem', 'Omegacin', 'Panipenem', 'Carbenin', 'Razupenem',
  'Sulbactam', 'Unasyn', 'Tazobactam', 'Zosyn', 'Clavulanate', 'Augmentin',
  'Avibactam', 'Avycaz', 'Relebactam', 'Recarbrio', 'Vaborbactam', 'Vabomere',
  'Metronidazole', 'Flagyl', 'MetroCream', 'MetroGel', 'Noritate', 'Vandazole',
  'Tinidazole', 'Tindamax', 'Fasigyn', 'Ornidazole', 'Tiberal', 'Secnidazole',
  'Solosec', 'Satranidazole', 'Satra', 'Nitazoxanide', 'Alinia', 'Nizonide',
  'Nitazox', 'Sulfamethoxazole', 'Gantanol', 'Trimethoprim', 'Proloprim',
  'Trimpex', 'CoTrimoxazole', 'Bactrim', 'Septra', 'Sulfadiazine', 'Microsulfon',
  'Sulfisoxazole', 'Gantrisin', 'Sulfasalazine', 'Azulfidine', 'Sulfadoxine',
  'Fansidar', 'Dapsone', 'Aczone', 'Avlosulfon', 'Sulfametopyrazine',
  'Vancomycin', 'Vancocin', 'Firvanq', 'Vancomax', 'Linezolid', 'Zyvox',
  'Zyvoxid', 'Tedizolid', 'Sivextro', 'Sutezolid', 'PNU100', 'Cycloserine',
  'Seromycin', 'Dizole', 'Fosfomycin', 'Monurol', 'Fomicyt', 'Fosfocin',
  'Colistin', 'ColyMycin', 'Colobreathe', 'Tobramycin', 'Tobi', 'Bethkis',
  'Kitabis', 'Gentamicin', 'Garamycin', 'Cidomycin', 'Amikacin', 'Amikin',
  'Arikayce', 'Kanamycin', 'Kantrex', 'Streptomycin', 'Neomycin', 'Mycifradin',
  'NeoFradin', 'Paromomycin', 'Humatin', 'Spectinomycin', 'Trobicin',
  'Chloramphenicol', 'Chloromycetin', 'Chlorcol', 'Chlorsig', 'Clindamycin',
  'Cleocin', 'Clindagel', 'Clindesse', 'Evoclin', 'Dalacin', 'Lincomycin',
  'Lincocin', 'Lincorex', 'Dalfopristin', 'Quinupristin', 'Synercid',
  'Mupirocin', 'Bactroban', 'Centany', 'Mupinase', 'Bacitracin', 'Polysporin',
  'Neosporin', 'Tyrothricin', 'Gramicidin', 'PolymyxinB', 'Polytracin',
  'Papulacandin', 'Echinocandin', 'Caspofungin', 'Cancidas', 'Micafungin',
  'Mycamine', 'Anidulafungin', 'Eraxis', 'Rezafungin', 'Rezzayo',
  'Ibrexafungerp', 'Brexafemme', 'Fosmanogepix', 'Olorofim', 'Voriconazole',
  'Vfend', 'Posaconazole', 'Noxafil', 'Isavuconazole', 'Cresemba', 'Itraconazole',
  'Sporanox', 'Tolsura', 'Fluconazole', 'Diflucan', 'Ketoconazole', 'Nizoral',
  'Noxafil', 'Posaconazole', 'Miconazole', 'Monistat', 'Daktarin', 'Oravig',
  'Econazole', 'Ecoza', 'Spectazole', 'Terbinafine', 'Lamisil', 'Terbinaforce',
  'Butenafine', 'Mentax', 'Naftifine', 'Naftin', 'Tolnaftate', 'Tinactin',
  'Aftate', 'Ciclopirox', 'Loprox', 'Penlac', 'Ciloxan', 'Amorolfine',
  'Loceryl', 'Curanail', 'Amorolfine', 'Griseofulvin', 'GrisPEG', 'Grifulvin',
  'Fulvicin', 'Flucytosine', 'Ancobon', 'Crypoto', 'PotassiumIodide', 'SSKI',
  'Pima', 'Corticotropin', 'ACTH', 'Acthar', 'Cosyntropin', 'Cortrosyn',
  'Tetracosactrin', 'Synacthen', 'Desmopressin', 'DDAVP', 'Minirin', 'Stimate',
  'Vasopressin', 'Pitressin', 'Terlipressin', 'Glypressin', 'Lypressin',
  'Diazoxide', 'Proglycem', 'Glucagon', 'Glucagen', 'GlucaGen', 'Baqsimi',
  'Gonadorelin', 'Factrel', 'Lutrepulse', 'Goserelin', 'Zoladex', 'Buserelin',
  'Suprefact', 'Histrelin', 'Supprelin', 'Vantas', 'Leuprolide', 'Lupron',
  'Eligard', 'Triptorelin', 'Trelstar', 'Decapeptyl', 'Nafarelin', 'Synarel',
  'Deslorelin', 'Ovuplant', 'Abarelix', 'Plenaxis', 'Degarelix', 'Firmagon',
  'Relugolix', 'Orgovyx', 'Cetrorelix', 'Cetrotide', 'Ganirelix', 'Antagon',
  'Clomiphene', 'Clomid', 'Serophene', 'Letrozole', 'Femara', 'Anastrozole',
  'Arimidex', 'Exemestane', 'Aromasin', 'Tamoxifen', 'Nolvadex', 'Soltamox',
  'Toremifene', 'Fareston', 'Raloxifene', 'Evista', 'Bazedoxifene', 'Duavee',
  'Ulipristal', 'Ella', 'Fibristal', 'Mifepristone', 'Mifeprex', 'Korlym',
  'Megestrol', 'Megace', 'MegaceES', 'Hydroxyprogesterone', 'Makena',
  'Progesterone', 'Prometrium', 'Crinone', 'Endometrin', 'Prochieve',
  'Norethisterone', 'Aygestin', 'Camila', 'Errin', 'Jencycla', 'Norlutate',
  'PrimolutN', 'Norgestrel', 'Ovrette', 'Levonorgestrel', 'PlanB', 'Mirena',
  'Skyla', 'Kyleena', 'Liletta', 'ParaGard', 'Etonogestrel', 'Implanon',
  'Nexplanon', 'Nestorone', 'Tanaproget', 'Nomegestrol', 'Nomegestrol',
  'Dienogest', 'Visanne', 'Natazia', 'Drospirenone', 'Yasmin', 'Yaz', 'Angelique',
  'Slynd', 'Desogestrel', 'Cerazette', 'Mercilon', 'Marvelon', 'Cyproterone',
  'Diane35', 'Dianette', 'Chlormadinone', 'Belara', 'Oralcon', 'Estradiol',
  'Estrace', 'Estraderm', 'Climara', 'Vivelle', 'Minivelle', 'Alora',
  'Menostar', 'Divigel', 'Elestrin', 'Estrasorb', 'Evamist', 'Estrogel',
  'Estring', 'Femring', 'Vagifem', 'Premarin', 'Cenestin', 'Enjuvia',
  'Premphase', 'Prempro', 'Femhrt', 'Activella', 'Angeliq', 'ClimaraPro',
  'Estalis', 'Combipatch', 'Duavee', 'Bijuva', 'Estradiol', 'Gynodian',
  'EstradiolValerate', 'Progynova', 'EstradiolCypionate', 'DepoEstradiol',
  'EstradiolBenzoate', 'EstradiolEnanthate', 'DHEA', 'Prasterone', 'Intrarosa',
  'Testosterone', 'AndroGel', 'Testim', 'Axiron', 'Fortesta', 'Natesto',
  'Striant', 'Androderm', 'Testoderm', 'DepoTestosterone', 'Delatestryl',
  'Nebido', 'Aveed', 'Androxy', 'Methitest', 'Android', 'Testred', 'Virilon',
  'Stanolone', 'Andractim', 'Mesterolone', 'Proviron', 'Danazol', 'Danocrine',
  'Cyclomen', 'Oxandrolone', 'Oxandrin', 'Anavar', 'Oxymetholone', 'Anadrol',
  'Stanozolol', 'Winstrol', 'Boldenone', 'Equipoise', 'Nandrolone', 'DecaDurabolin',
  'Durabolin', 'Trenbolone', 'Finaplix', 'Drostanolone', 'Masteron',
  'Methyltestosterone', 'Norethandrolone', 'Nilevar', 'Ethynodiol', 'Ovulen',
  'TripleEstrogen', 'TriEst', 'Biest', 'Estratest', 'Covaryx', 'EsterifiedEstrogens',
  'Estratab', 'Menest', 'Pantethine', 'Pantosin', 'Pantesin', 'Carnitine',
  'Carnitor', 'Lactinol', 'ALC', 'POA', 'Creatine', 'CreatineMonohydrate',
  'CreatinePhosphate', 'Neoton', 'CoenzymeQ10', 'CoQ10', 'Ubiquinone',
  'Ubiquinol', 'Qunol', 'MitoQ', 'Idebenone', 'Catena', 'Raxone', 'Sovrima',
  'Nexin', 'Melatonin', 'Circadin', 'Slenyto', 'Cilansetron', 'Ondansetron',
  'Zofran', 'Zuplenz', 'Anzemet', 'Dolasetron', 'Granisetron', 'Kytril',
  'Sancuso', 'Palonosetron', 'Aloxi', 'Akynzeo', 'Netupitant', 'Fosaprepitant',
  'Emend', 'Cinvanter', 'Rolapitant', 'Varubi', 'Aprepitant', 'Emend',
  'Nabilone', 'Cesamet', 'Dronabinol', 'Marinol', 'Syndros', 'Loperamide',
  'Imodium', 'Diacare', 'Lomotil', 'Diphenoxylate', 'Lomotil', 'Codeine',
  'Paregoric', 'OpiumTincture', 'Laudanum', 'BismuthSubsalicylate', 'PeptoBismol',
  'Kaopectate', 'Kaolin', 'Pectin', 'Donnatal', 'Bentyl', 'Dicyclomine',
  'Hyoscyamine', 'Levsin', 'Levbid', 'NuLev', 'Oscimin', 'Anaspaz',
  'Cystospaz', 'Donnatab', 'Symax', 'Chlordia', 'Scopolamine', 'TransdermScop',
  'Maldemar', 'Buscopan', 'Hyoscine', 'Pamine', 'Methscopolamine', 'Prostigmin',
  'Neostigmine', 'Pyridostigmine', 'Mestinon', 'Regonol', 'DuVoid', 'Urecholine',
  'Bethanechol', 'Bethanecol', 'Myotonachol', 'Carbachol', 'Miostat', 'IsoptoCarbachol',
  'Micura', 'Pilocarpine', 'IsoptoCarpine', 'Pilopine', 'Salagen', 'Pilocar',
  'Cevimeline', 'Evoxac', 'AnetholeTrithione', 'Sialor', 'Arcalion', 'Sulbutiamine',
  'Enada', 'NADH', 'Nicotinamide', 'Niacinamide', 'NicotinicAcid', 'Niacin',
  'Niaspan', 'Simcor', 'Advicor', 'Inositol', 'Citicoline', 'CDPCholine',
  'Ceraxon', 'Somazina', 'Xerenoos', 'Cognizin', 'AlphaGPC', 'LAlphaGlyceryl',
  'GPC', 'CholineAlfoscerate', 'Gliatilin', 'Bidil', 'Hydralazine', 'Apresoline',
  'Minoxidil', 'Loniten', 'Rogaine', 'Procardia', 'Nifedipine', 'Adalat',
  'Amlodipine', 'Norvasc', 'Katerzia', 'Felodipine', 'Plendil', 'Isradipine',
  'DynaCirc', 'Nicardipine', 'Cardene', 'Nimodipine', 'Nimotop', 'Nymalize',
  'Nisoldipine', 'Sular', 'Nitrendipine', 'Baypress', 'Lacidipine', 'Motens',
  'Lercanidipine', 'Zanidip', 'Lercapin', 'Manidipine', 'Madipine', 'Clevidipine',
  'Cleviprex', 'Diltiazem', 'Cardizem', 'Tiazac', 'Dilacor', 'Cartia', 'Matzim',
  'Verapamil', 'Calan', 'Isoptin', 'Verelan', 'Covera', 'Calcitriol', 'Rocaltrol',
  'Vectical', 'Calcijex', 'Doxercalciferol', 'Hectorol', 'Paricalcitol', 'Zemplar',
  'Cinacalcet', 'Sensipar', 'Mimpara', 'Etelcalcetide', 'Parsabiv', 'Evocalcet',
  'Alfacalcidol', 'OneAlpha', 'AlphaD3', 'Bonalfa', 'Didroquyl', 'Dihydrotachysterol',
  'Hytakerol', 'Calcifediol', 'Calderol', 'Dediol', 'Ergocalciferol', 'Drisdol',
  'Calciferol', 'Cholecalciferol', 'VitaminD3', 'Decara', 'D3Drops',
  'Calcipotriene', 'Dovonex', 'Calcitrene', 'Sorilux', 'Taclonex', 'Tacalcitol',
  'Bonalfa', 'Maxacalcitol', 'Prezios', 'Oxacalcitriol', 'OxyCal',
  'Sevelamer', 'Renagel', 'Renvela', 'Lanthanum', 'Fosrenol', 'CalciumAcetate',
  'PhosLo', 'Eliphos', 'Calphron', 'CalciumCarbonate', 'Tums', 'OsCal',
  'Caltrate', 'CalciumCitrate', 'Citracal', 'MagnesiumCarbonate',
  'MagnesiumOxide', 'MagOx', 'UroMag', 'MagnesiumSulfate', 'EpsomSalt',
  'MagnesiumGluconate', 'Magonate', 'AluminumHydroxide', 'Amphojel', 'AlternaGEL',
  'AluCap', 'Basaljel', 'SodiumPolystyreneSulfonate', 'Kayexalate', 'Kionex',
  'Patiromer', 'Veltassa', 'SodiumZirconiumCyclosilicate', 'Lokelma',
  'ZincSulfate', 'Zincate', 'Zinc220', 'ZincGluconate', 'ZincPiccolinate',
  'Copper', 'Cuprimine', 'Depen', 'Syprine', 'Trientine', 'Heparin',
  'HepFlush', 'HepLock', 'Liquaemin', 'Enoxaparin', 'Lovenox', 'Clexane',
  'Heparinoid', 'Danaparoid', 'Orgaran', 'Fondaparinux', 'Arixtra', 'Hedex',
  'Pamprin', 'Midol', 'Panadol', 'Tylenol', 'Anacin', 'Excedrin', 'Vanquish',
  'Contac', 'Sudafed', 'Pseudoephedrine', 'Phenylephrine', 'Diphenhydramine',
  'Benadryl', 'Unisom', 'Nytol', 'ZzzQuil', 'Sominex', 'Chlorpheniramine',
  'ChlorTrimeton', 'Polaramine', 'Dexchlorpheniramine', 'Loratadine', 'Claritin',
  'Alavert', 'Desloratadine', 'Clarinex', 'Aerius', 'Cetirizine', 'Zyrtec',
  'Reactine', 'Fexofenadine', 'Allegra', 'Telfast', 'Levocetirizine', 'Xyzal',
  'Bilastine', 'Bilaxten', 'Ilevro', 'Ketotifen', 'Zaditor', 'Alaway',
  'Patanol', 'Olopatadine', 'Pazeo', 'Pataday', 'Epinastine', 'Elestat',
  'Azelastine', 'Astelin', 'Optivar', 'Astapro', 'Bepotastine', 'Bepreve',
  'Alcaftadine', 'Lastacaft', 'Cromolyn', 'NasalCrom', 'OptiCrom', 'Gastrocrom',
  'Nedocromil', 'Alocril', 'Tilade', 'Lodoxamide', 'Alomide', 'Alamast',
  'Pemirolast', 'Alamast', 'Budesonide', 'Rhinocort', 'Fluticasone', 'Flonase',
  'Flixonase', 'Mometasone', 'Nasonex', 'Beclomethasone', 'Beconase', 'Qnasl',
  'Triamcinolone', 'Nasacort', 'AllerNaze', 'Ciclesonide', 'Omnaris', 'Zetonna',
  'Olopatadine', 'Patanase', 'Azelastine', 'Astelin', 'Stepin', 'Dymista',
  'Zalviso', 'Sufentanil', 'Dsuvia', 'Fentanyl', 'Duragesic', 'Sublimaze',
  'Actiq', 'Fentora', 'Onsolis', 'Abstral', 'Lazanda', 'Subsys', 'Ionsys',
  'Morphine', 'MSContin', 'Oramorph', 'Kadian', 'Avinza', 'Arymo', 'MorphaBond',
  'Moxduo', 'Embeda', 'Morphine', 'Roxanol', 'Infumorph', 'Duramorph',
  'Codeine', 'CodeineContin', 'Oxymorphone', 'Opana', 'Numorphan',
  'Hydromorphone', 'Dilaudid', 'Exalgo', 'Hydrostat', 'Meperidine', 'Demerol',
  'Pethidine', 'Meperitab', 'Methadone', 'Dolophine', 'Methadose', 'Diskets',
  'Levorphanol', 'LevoDromoran', 'Butorphanol', 'Stadol', 'Nalbuphine', 'Nubain',
  'Pentazocine', 'Talwin', 'TalwinNX', 'Dezocine', 'Dalgan', 'Buprenorphine',
  'Buprenex', 'Butrans', 'Subutex', 'Probuphine', 'Sublocade', 'Suboxone',
  'Zubsolv', 'Bunavail', 'Cassipa', 'Naloxone', 'Narcan', 'Evzio', 'Kloaxado',
  'Naltrexone', 'ReVia', 'Vivitrol', 'Depade', 'Nalmefene', 'Selincro',
  'Lofexidine', 'Lucemyra', 'Lofexidine', 'Benzodiazepine', 'Alprazolam',
  'Xanax', 'Niravam', 'Chlordiazepoxide', 'Librium', 'Limbritrol', 'Clonazepam',
  'Klonopin', 'Rivotril', 'Clorazepate', 'Tranxene', 'Diazepam', 'Valium',
  'Diastat', 'Estazolam', 'Prosom', 'Flurazepam', 'Dalmane', 'Halazepam',
  'Paxipam', 'Ketazolam', 'Loftran', 'Lorazepam', 'Ativan', 'Loxapine',
  'Oxazepam', 'Serax', 'PrazePAM', 'Centrax', 'Quazepam', 'Doral',
  'Temazepam', 'Restoril', 'Triazolam', 'Halcion', 'Midazolam', 'Versed',
  'Dormicum', 'Flunitrazepam', 'Rohypnol', 'Nitrazepam', 'Mogadon', 'Alodorm',
  'Insoma', 'Remace', 'Zopiclone', 'Imovane', 'Zimovane', 'Eszopiclone',
  'Lunesta', 'Zaleplon', 'Sonata', 'Zolpidem', 'Ambien', 'Edluar', 'Intermezzo',
  'Zolpimist', 'Sublinox', 'Ramelteon', 'Rozerem', 'Suvorexant', 'Belsomra',
  'Doxepin', 'Silenor', 'Trazodone', 'Desyrel', 'Oleptro', 'Mirtazapine',
  'Remeron', 'RemeronSolTab', 'Hydroxyzine', 'Atarax', 'Vistaril', 'Vistazine',
  'Promethazine', 'Phenergan', 'Promethegan', 'Prothiazine', 'Procalm',
];

const generics = [
  'Acetaminophen', 'Ibuprofen', 'Aspirin', 'Naproxen', 'Diclofenac', 'Mefenamic Acid',
  'Paracetamol', 'Amoxicillin', 'Amoxicillin + Clavulanic Acid', 'Cephalexin', 'Azithromycin',
  'Ciprofloxacin', 'Levofloxacin', 'Metronidazole', 'Clarithromycin', 'Erythromycin',
  'Doxycycline', 'Clindamycin', 'Sulfamethoxazole + Trimethoprim', 'Nitrofurantoin',
  'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Miconazole', 'Nystatin',
  'Ketoconazole', 'Griseofulvin', 'Omeprazole', 'Esomeprazole', 'Lansoprazole',
  'Pantoprazole', 'Rabeprazole', 'Ranitidine', 'Famotidine', 'Cimetidine',
  'Domperidone', 'Metoclopramide', 'Ondansetron', 'Loperamide', 'Bismuth Subsalicylate',
  'Dicyclomine', 'Hyoscyamine', 'Ursodeoxycholic Acid', 'Mesalamine', 'Sulfasalazine',
  'Prednisone', 'Methylprednisolone', 'Dexamethasone', 'Hydrocortisone', 'Betamethasone',
  'Amlodipine', 'Lisinopril', 'Losartan', 'Valsartan', 'Candesartan', 'Irbesartan',
  'Telmisartan', 'Enalapril', 'Ramipril', 'Captopril', 'Metoprolol', 'Atenolol',
  'Propranolol', 'Bisoprolol', 'Carvedilol', 'Diltiazem', 'Verapamil', 'Nifedipine',
  'Hydrochlorothiazide', 'Furosemide', 'Spironolactone', 'Atorvastatin', 'Simvastatin',
  'Rosuvastatin', 'Pravastatin', 'Fluvastatin', 'Pitavastatin', 'Metformin',
  'Glimepiride', 'Gliclazide', 'Glipizide', 'Sitagliptin', 'Vildagliptin',
  'Saxagliptin', 'Linagliptin', 'Empagliflozin', 'Dapagliflozin', 'Canagliflozin',
  'Insulin Glargine', 'Insulin Detemir', 'Insulin Aspart', 'Insulin Lispro',
  'Insulin Regular', 'Insulin NPH', 'Levothyroxine', 'Methimazole', 'Propylthiouracil',
  'Alendronate', 'Risedronate', 'Zoledronic Acid', 'Calcium Carbonate', 'Vitamin D3',
  'Warfarin', 'Heparin', 'Enoxaparin', 'Clopidogrel', 'Ticagrelor', 'Prasugrel',
  'Aspirin', 'Dipyridamole', 'Digoxin', 'Amiodarone', 'Lidocaine', 'Flecainide',
  'Propafenone', 'Albuterol', 'Salbutamol', 'Ipratropium', 'Tiotropium', 'Fluticasone',
  'Budesonide', 'Mometasone', 'Montelukast', 'Theophylline', 'Aminophylline',
  'Diphenhydramine', 'Loratadine', 'Cetirizine', 'Fexofenadine', 'Desloratadine',
  'Levocetirizine', 'Fluoxetine', 'Sertraline', 'Citalopram', 'Escitalopram',
  'Paroxetine', 'Venlafaxine', 'Duloxetine', 'Bupropion', 'Mirtazapine',
  'Amitriptyline', 'Nortriptyline', 'Imipramine', 'Clomipramine', 'Trazodone',
  'Haloperidol', 'Risperidone', 'Olanzapine', 'Quetiapine', 'Aripiprazole',
  'Clozapine', 'Ziprasidone', 'Paliperidone', 'Lithium Carbonate',
  'Alprazolam', 'Lorazepam', 'Diazepam', 'Clonazepam', 'Oxazepam', 'Temazepam',
  'Chlordiazepoxide', 'Zolpidem', 'Zopiclone', 'Eszopiclone', 'Pregabalin',
  'Gabapentin', 'Carbamazepine', 'Valproic Acid', 'Lamotrigine', 'Topiramate',
  'Levetiracetam', 'Phenytoin', 'Oxycodone', 'Hydrocodone', 'Morphine', 'Codeine',
  'Fentanyl', 'Meperidine', 'Tramadol', 'Methadone', 'Buprenorphine', 'Naloxone',
  'Naltrexone', 'Baclofen', 'Tizanidine', 'Cyclobenzaprine', 'Methocarbamol',
  'Carisoprodol', 'Dantrolene', 'Allopurinol', 'Febuxostat', 'Colchicine',
  'Hydroxychloroquine', 'Methotrexate', 'Azathioprine', 'Cyclosporine', 'Mycophenolate',
  'Tacrolimus', 'Sirolimus', 'Prednisolone', 'Triamcinolone', 'Meloxicam',
  'Celecoxib', 'Etoricoxib', 'Indomethacin', 'Sulindac', 'Piroxicam', 'Ketorolac',
  'Cyclobenzaprine', 'Capsaicin', 'Methylcobalamin', 'Cyanocobalamin', 'Folic Acid',
  'Ferrous Sulfate', 'Ferrous Gluconate', 'Iron Dextran', 'Iron Sucrose',
  'Vitamin B1', 'Vitamin B6', 'Vitamin B12', 'Vitamin C', 'Vitamin E', 'Multivitamin',
  'Zinc Sulfate', 'Zinc Gluconate', 'Magnesium Oxide', 'Potassium Chloride',
  'Sodium Chloride', 'Ondansetron', 'Metoclopramide', 'DimethylDRINATE', 'Promethazine',
  'Benzonatate', 'Dextromethorphan', 'Guaifenesin', 'Pseudoephedrine', 'Phenylephrine',
  'Lactulose', 'Polyethylene Glycol', 'Bisacodyl', 'Senna', 'Psyllium', 'Docusate',
  'Ketorolac', 'Tropicamide', 'Pilocarpine', 'Timolol', 'Latanoprost', 'Bimatoprost',
  'Travoprost', 'Dorzolamide', 'Brinzolamide', 'Ofloxacin', 'Moxifloxacin',
  'Tobramycin', 'Ciprofloxacin', 'Gentamicin', 'Prednisolone Acetate', 'Loteprednol',
];

const companies = [
  'Abbott Laboratories', 'GlaxoSmithKline', 'Pfizer', 'Novartis', 'Sanofi',
  'Merck', 'AstraZeneca', 'Bayer', 'Roche', 'Eli Lilly', 'Getz Pharma',
  'Bosch Pharmaceuticals', 'Highnoon Laboratories', 'Ferozsons Laboratories',
  'Wilson Industries', 'Martin Dow', 'PharmEvo', 'Shroog Pharmaceuticals',
  'Zafa Pharmaceuticals', 'Ideal Pharmaceuticals', 'Platinum Pharmaceuticals',
  'Beacon Pharma', 'Sami Pharmaceuticals', 'Tabro Pharma', 'Searle Pakistan',
  'AGP Limited', 'Accuray Laboratories', 'Al Habib Pharma', 'AL-HAMD Pharma',
  'Amis Pharma', 'Amson Vaccines', 'Argent Pharmaceuticals', 'Asian Pharma',
  'Avant Pharma', 'Avison Laboratories', 'Batala Pharma', 'Bell Pharma',
  'Biocare', 'BioFarma', 'Chenab Pharma', 'Citi Pharma', 'Continental Pharma',
  'Crystol Pharma', 'CSAH Pharma', 'Curis Pharma', 'Danas pharmaceuticals',
  'Davos Pharma', 'Devine Pharma', 'Dickson Pharma', 'Dolphin Pharma',
  'Dosaco Pharma', 'Dyson Pharma', 'Effex Pharma', 'EG Pharma', 'Elko Pharma',
  'Emerald Pharma', 'Epoch Pharma', 'Evento Pharma', 'Excel Pharma',
  'Exquis Pharma', 'Fertima Pharma', 'Futura Pharma', 'Gaba Pharma',
  'Genesis Pharma', 'Global Pharma', 'Grace Pharma', 'Grays Pharma',
  'Helix Pharma', 'Hemani Pharma', 'Hilton Pharma', 'IBNs Pharma',
  'Immuno Pharma', 'Indus Pharma', 'Irza Pharma', 'Jawa Pharma',
  'Jinnah Pharma', 'Kalsoom Pharma', 'Karachi Pharma', 'Kiran Pharma',
  'Kohinoor Pharma', 'Kramer Pharma', 'Labmate Pharma', 'Leads Pharma',
  'Limelight Pharma', 'Luton Pharma', 'Macter International', 'Marcas Pharma',
  'Matrix Pharma', 'Maxitech Pharma', 'MediAsia Pharma', 'Medipak Pharma',
  'Mega Pharma', 'Mercury Pharma', 'Micro Labs', 'Midwest Pharma',
  'Millat Pharma', 'Mission Pharma', 'Molsons Pharma', 'Mumtaz Pharma',
  'Munawar Pharma', 'Mundipharma', 'Mustafa Pharma', 'Mylan Pharmaceuticals',
  'Nabiqasim Pharma', 'Nexus Pharma', 'Nimrall Laboratories', 'Novin Pharma',
  'Novo Pharma', 'OBS Pharma', 'Octax Pharma', 'Olayan Pharma', 'Orient Pharma',
  'Ozone Pharma', 'Pacific Pharma', 'PACE Pharmaceuticals', 'Parkin Pharma',
  'Peak Pharma', 'Pearl Pharma', 'Pharma Wisdom', 'Pharmadic Laboratories',
  'Pharmacare Laboratories', 'Pinnacle Pharmaceuticals', 'Pioneer Pharma',
  'Pulse Pharma', 'Punjab Pharma', 'Qaiser Pharma', 'Quraish Pharma',
  'Ray Pharma', 'Reagan Pharma', 'Regent Pharma', 'Remington Pharma',
  'Rep-ko Pharma', 'Rex Pharma', 'Rock Pharma', 'Roryan Pharma', 'Sabeen Pharma',
  'Saffron Pharma', 'Sage Pharma', 'Salam Pharma', 'Salem Pharma', 'Sami Pharma',
  'Sana Pharma', 'Sante Pharma', 'Sapphire Pharma', 'Schafer Pharma',
  'Schazoo Laboratories', 'Sebro Pharma', 'Seliton Pharma', 'Servier Pakistan',
  'Seven Pharma', 'Shalimar Pharma', 'Shifa Pharma', 'Shroog Pharma',
  'Sidco Laboratories', 'Silarx Pharma', 'Silver Pharma', 'Siza Pharma',
  'Skylab Pharma', 'Smart Pharma', 'Snapha Pharma', 'Softech Pharma',
  'Sogrand Pharma', 'Sohail Pharma', 'Sonex Pharma', 'Stallion Pharma',
  'Standpharma', 'Star Labs', 'Sterile Pharma', 'Stellapharm', 'Steroid Pharma',
  'Sufi Pharma', 'Suleman Pharma', 'Sun Pharma', 'Superior Pharma',
  'Surge Laboratories', 'Swiss Pharma', 'Sytheon Pharma', 'Tabro Pharma',
  'Tagma Pharma', 'Talkha Pharma', 'Taurus Pharma', 'Tech Pharma',
  'Terrace Pharma', 'Thalvena Pharma', 'Theon Pharma', 'Theseo Pharma',
  'TIM Pharma', 'Toscana Pharma', 'Tower Pharma', 'Triple-O Pharma',
  'Trust Pharma', 'Ultra Pharma', 'Unique Pharma', 'United Pharma',
  'Universal Pharma', 'Urasia Pharma', 'Urban Pharma', 'Valor Pharma',
  'Venus Pharma', 'Vertex Pharma', 'Vest Pharma', 'Vetcare Pharma',
  'Vigilant Pharma', 'Vincent Pharma', 'Vita Pharma', 'Vizier Pharma',
  'Wellcome Pharma', 'Wise Pharma', 'Wns Pharma', 'Wuhan Pharma',
  'Xenon Pharma', 'Xpert Pharma', 'Yamanaka Pharma', 'Zafa Pharma',
  'Zee Laboratories', 'Zeon Pharmaceuticals', 'Zeus Pharma', 'Zinc Pharma',
  'Zion Pharma', 'Zita Pharma', 'Zolux Pharma', 'Zubair Pharma',
  'Cipla Pakistan', 'Dr Reddys Laboratories', 'Sun Pharmaceutical Industries',
  'Lupin Pakistan', 'Zydus Cadila', 'Torrent Pharmaceuticals', 'Aurobindo Pharma',
  'Hetero Drugs', 'Emcure Pharmaceuticals', 'Alcon Pakistan', 'Baxter Pakistan',
  'B Braun Pakistan', 'Fresenius Kabi', 'Johnson & Johnson', 'Bristol Myers Squibb',
  'Novo Nordisk', 'Boehringer Ingelheim', 'Takeda Pakistan', 'AbbVie Pakistan',
  'Gilead Sciences', 'Amgen Pakistan', 'Biogen Pakistan', 'Celgene Pakistan',
  'Teva Pharmaceuticals', 'Sandoz Pakistan', 'Mylan Pakistan', 'Viatris Pakistan',
];

function shuffle(a) {
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

async function main() {
  const count = await prisma.masterMedicineList.count();
  if (count > 0) {
    console.log(`Master list already has ${count} entries — skipping seed.`);
    return;
  }

  await prisma.masterMedicineList.deleteMany();

  const usedBrands = new Set();
  const entries = [];

  for (let i = 0; i < brands.length && entries.length < 1100; i++) {
    const base = brands[i];
    const brandName = base;
    if (usedBrands.has(brandName.toLowerCase())) continue;
    usedBrands.add(brandName.toLowerCase());
    entries.push({
      brandName,
      genericName: generics[i % generics.length],
      companyName: companies[i % companies.length],
    });
  }

  // Fill remaining up to 1100 with brand + variant numbers
  let suffix = 1;
  while (entries.length < 1100) {
    const base = brands[entries.length % brands.length];
    const brandName = `${base} ${suffix}`;
    if (usedBrands.has(brandName.toLowerCase())) { suffix++; continue; }
    usedBrands.add(brandName.toLowerCase());
    entries.push({
      brandName,
      genericName: generics[entries.length % generics.length],
      companyName: companies[entries.length % companies.length],
    });
    suffix++;
  }

  await prisma.masterMedicineList.createMany({ data: entries });
  console.log(`Seeded ${entries.length} master medicines.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
